#!/bin/sh

if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

if [ ! -z "$TRAVIS" ]
then # Running on Travis CI
    # Fail on first error code
    # Print each command
    set -ev
else # Running locally
    # Fail on first error code
    set -e

    # Redirect output to stderr.
    exec 1>&2

    # Check for whitespace errors (ignoring node_modules)
    git diff-index --check --cached $against -- app config cron public tasks test views .gitignore .ruby-version .travis.yml CONTRIBUTING.md Gemfile Gemfile.lock LICENSE README.md Rakefile app.js fabfile.py package.json npm-shrinkwrap.json
fi

ruby -c Gemfile >/dev/null
ruby -c config/environment.rb >/dev/null
ruby -c tasks/elasticsearch.rake >/dev/null
ruby -c tasks/sitemap.rake >/dev/null
ruby -c tasks/aws.rake >/dev/null
node_modules/jshint/bin/jshint app.js app/*.js config/config.js tasks/*.js test/*.js
tasks/validate-json.js
tasks/jshint-ejs.js views/layout/footer.html views/layout/header.html views/index.html views/inspector.html views/inspectors.html views/report.html views/reports.html views/reports.xml.ejs views/dashboard.html
