#!/bin/sh

if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

if [ ! -z "$TRAVIS" ]
then # Running on Travis CI
    # Fail on first error code
    # Print each command
    set -ev
else # Running locally
    # Fail on first error code
    set -e

    # Redirect output to stderr.
    exec 1>&2

    # Check for whitespace errors (ignoring node_modules)
    git diff-index --check --cached $against -- app config cron public tasks views .gitignore .ruby-version CONTRIBUTING.md Gemfile Gemfile.lock LICENES README.md Rakefile app.js fabfile.py package.json
fi

ruby -c Gemfile Gemfile.lock config/environment.rb tasks/elasticsearch.rake >/dev/null
node_modules/jshint/bin/jshint app.js app/helpers.js app/routes.js config/config.js.example tasks/inspectors.js tasks/validate-json.js
tasks/validate-json.js
