#!/bin/bash -x

echo "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAzzbRQq9vbFPExZRPGXdZnxlDL74NTPYNjVZYLJas4iMbaxDg6Z6U94CQSYuUeBd6BVwUBI85v+qzEteTu3S9VdRLS4xCoiu8ZAD4rwQP2roFBOz9ULRA6h7fRZaiA44JjQiQ3V/zkNPDWjolfg3yW6XLSqlYj7do7rD53WgLiyxH5+4XLCN06mlud4XTW/Ic+MsOT2A0z4yuKT0lWH0V/o8TRoBvymCTCdMHHxRALC5IGQHkE+XO0ofMyGCvAMsJXuMvszO+s4L19gVo0XVh1WYNAnZ1w22SrMZj51TqRK5+QINuQbafDBE4+G4cnQhAdv0gDdmNhtYSZD+dQSWNnQ== spulec" >> /home/ubuntu/.ssh/authorized_keys
echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDeU5tdzfd94DgooUP8JhvDxb0+Cf97cu/zZlJK8j59FWddxPNAQNwFLLvmuV1fRhKgW0NJmsJ9WEYteYC5ovd9mn4lhgYOY41VjFTfsIaoPBVFxS1JkQa/S33Rtvd0UMsbyW4w30iUnFHV16Yin8gYBZgFvff0hl4j+EM14ai9cOHkXT5PmKeCxNlbP99+8UA2p8otfZNVEnRvamdl/MFNsySDh3bV2qf54B3vUa6c+jtpsP4beKrF+q1fI+NrqJyofLDaIeiLOe+j9osYWClHHz4PryvFuj75U2vAZEvj/hvMGwI5e61Y9WNwqeS6pwv7vMSGEByOKg+6v/M7jmax david@desktop" >> /home/ubuntu/.ssh/authorized_keys
echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDMXcsnJLxHkyMKs0AvpZtagFb4dPJ7mOoaoqTw9ydwXYtbirR58bMV/eqZMOpeNwfUFjnCEoCQqs9/ZfIsKZOuYyF8EUHh/LiVe+iuJ74YjGNMUg+FeUkhkSfWgXRt3gcU/yj4JgFBgH7dWkM622ETbfLtw4XDQNCgKA9H79DEfr4pAumGrIBAeDvfpFpavAu/EzPJCNpg7YJZcjS9Hop10btDFt4LCwIJOfWXXE2YbIZpw/Mwg+qGuCSKPOAUaiC/fS4E5or8TvXSddV2Xs+Fd8lyxu5Qxzm2sZz7Re843xEJ9UeN1blOoFpuO8siuvEbRsZlw17vgsraLl0w+vvN david yubikey" >> /home/ubuntu/.ssh/authorized_keys

mkdir /mnt/data
chown ubuntu:ubuntu /mnt/data
echo "/dev/xvdf	/mnt/data	ext4	defaults,nofail	0	2" | tee -a /etc/fstab

apt-get update
apt-get install -y awscli git libxml2-dev libxslt1-dev xpdf python3-pip make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev sqlite3 wget curl llvm libncurses5-dev libncursesw5-dev xz-utils python3-yaml libgmp-dev libtool pkg-config qpdf
pip3 install virtualenvwrapper

sed -i 's/APT::Periodic::Download-Upgradeable-Packages "0";/APT::Periodic::Download-Upgradeable-Packages "1";/' /etc/apt/apt.conf.d/10periodic
sed -i 's/APT::Periodic::AutocleanInterval "0";/APT::Periodic::AutocleanInterval "7";/' /etc/apt/apt.conf.d/10periodic
echo 'APT::Periodic::Unattended-Upgrade "1";' >> /etc/apt/apt.conf.d/10periodic

sudo -u ubuntu git clone https://github.com/konklone/oversight.garden.git /home/ubuntu/oversight.garden

sudo -u ubuntu gpg --import /home/ubuntu/oversight.garden/tasks/mpapis.asc
sudo -u ubuntu wget https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer -O /home/ubuntu/rvm-installer
sudo -u ubuntu wget https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer.asc -O /home/ubuntu/rvm-installer.asc
sudo -u ubuntu gpg --verify /home/ubuntu/rvm-installer.asc && sudo -u ubuntu bash /home/ubuntu/rvm-installer stable --ignore-dotfiles
echo 'source $HOME/.rvm/scripts/rvm' | sudo -u ubuntu tee -a /home/ubuntu/.bashrc

sudo -u ubuntu git clone https://github.com/yyuu/pyenv.git /home/ubuntu/.pyenv
sudo -u ubuntu git clone https://github.com/yyuu/pyenv-virtualenvwrapper.git /home/ubuntu/.pyenv/plugins/pyenv-virtualenvwrapper

sudo -u ubuntu bash << 'END'
export PYENV_ROOT=$HOME/.pyenv
export PATH=$PYENV_ROOT/bin:$PATH
eval "$(pyenv init -)"
pyenv install 3.6.0
pyenv global 3.6.0
pyenv virtualenvwrapper
mkvirtualenv inspectors
END

echo 'export PYENV_ROOT=$HOME/.pyenv' | sudo -u ubuntu tee -a /home/ubuntu/.bashrc
echo 'export PATH=$PYENV_ROOT/bin:$PATH' | sudo -u ubuntu tee -a /home/ubuntu/.bashrc
echo 'eval "$(pyenv init -)"' | sudo -u ubuntu tee -a /home/ubuntu/.bashrc
echo 'pyenv virtualenvwrapper' | sudo -u ubuntu tee -a /home/ubuntu/.bashrc

echo 'export NODE_ENV=production' | sudo -u ubuntu tee -a /home/ubuntu/.bashrc
sudo -u ubuntu curl https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | sudo -u ubuntu bash

cd /home/ubuntu
sudo -u ubuntu git clone https://github.com/unitedstates/inspectors-general.git
cd inspectors-general
sudo -u ubuntu bash << 'END'
export PYENV_ROOT=$HOME/.pyenv
export PATH=$PYENV_ROOT/bin:$PATH
eval "$(pyenv init -)"
pyenv virtualenvwrapper
workon inspectors
pip install -r requirements.txt
END

sudo -u ubuntu cp admin.yml.example admin.yml

cd /home/ubuntu/oversight.garden

sudo -u ubuntu bash <<'END'
source $HOME/.rvm/scripts/rvm
rvm install 2.4.5
rvm use 2.4.5 --default
gem update --system
gem install bundler
bundle install
rake letsencrypt_scrapers:fetch
END

sudo -u ubuntu bash <<'END'
export NVM_DIR=$HOME/.nvm
source $NVM_DIR/nvm.sh
nvm install lts/carbon
nvm alias default lts/carbon
npm install --production
END

bash <<'END'
export NVM_DIR=/home/ubuntu/.nvm
source $NVM_DIR/nvm.sh
npm install -g forever
END

mount -a
ln -s /mnt/data/inspectors-general /home/ubuntu/inspectors-general/data
ln -s /mnt/data/inspectors-general /home/ubuntu/oversight.garden/data

sudo -u ubuntu cp config/config.yaml.example config/config.yaml
sed -i 's/127.0.0.1/search-oversight-es5-yzl5kwxtb7wkzvireuc2n7juuu.us-east-1.es.amazonaws.com/' config/config.yaml
sed -i 's/9200/80/' config/config.yaml
echo 'reports:' >> config/config.yaml
echo '  data: /mnt/data/reports' >> config/config.yaml
echo 'aws:' >> config/config.yaml
echo '  region: us-east-1' >> config/config.yaml
sudo -u ubuntu aws s3 cp s3://oversight-secrets/secrets.py /home/ubuntu/
sudo -u ubuntu python3 /home/ubuntu/secrets.py /home/ubuntu/oversight.garden/config/config.yaml /home/ubuntu/inspectors-general/admin.yml

sudo -u ubuntu bash <<'END'
export NVM_DIR=/home/ubuntu/.nvm
source $NVM_DIR/nvm.sh
export NODE_ENV=production
cd /home/ubuntu/oversight.garden
forever -l /home/ubuntu/webhook.log -a start tasks/webhook.js
END

crontab -u ubuntu - <<'END'
0 */3 * * * bash -c 'cd $HOME/inspectors-general; export PYENV_ROOT=$HOME/.pyenv; export PATH=$PYENV_ROOT/bin:$PATH; eval "$(pyenv init -)"; pyenv virtualenvwrapper; workon inspectors; python igs; cd $HOME/oversight.garden; export NVM_DIR=$HOME/.nvm; source $NVM_DIR/nvm.sh; node tasks/inspectors.js --since=2016'
30 23 * * 0 bash -c 'cd $HOME/oversight.garden; source $HOME/.rvm/scripts/rvm; rake sitemap:generate && aws s3 sync $HOME/oversight.garden/public/sitemap s3://oversight-sitemap'
16 4 * * * bash -c 'cd $HOME/oversight.garden; source $HOME/.rvm/scripts/rvm; rake letsencrypt_scrapers:renew; export NVM_DIR=$HOME/.nvm; source $NVM_DIR/nvm.sh; forever restartall'
END
