#!/bin/bash -x

echo "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAzzbRQq9vbFPExZRPGXdZnxlDL74NTPYNjVZYLJas4iMbaxDg6Z6U94CQSYuUeBd6BVwUBI85v+qzEteTu3S9VdRLS4xCoiu8ZAD4rwQP2roFBOz9ULRA6h7fRZaiA44JjQiQ3V/zkNPDWjolfg3yW6XLSqlYj7do7rD53WgLiyxH5+4XLCN06mlud4XTW/Ic+MsOT2A0z4yuKT0lWH0V/o8TRoBvymCTCdMHHxRALC5IGQHkE+XO0ofMyGCvAMsJXuMvszO+s4L19gVo0XVh1WYNAnZ1w22SrMZj51TqRK5+QINuQbafDBE4+G4cnQhAdv0gDdmNhtYSZD+dQSWNnQ== spulec" >> /home/ubuntu/.ssh/authorized_keys
echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDeU5tdzfd94DgooUP8JhvDxb0+Cf97cu/zZlJK8j59FWddxPNAQNwFLLvmuV1fRhKgW0NJmsJ9WEYteYC5ovd9mn4lhgYOY41VjFTfsIaoPBVFxS1JkQa/S33Rtvd0UMsbyW4w30iUnFHV16Yin8gYBZgFvff0hl4j+EM14ai9cOHkXT5PmKeCxNlbP99+8UA2p8otfZNVEnRvamdl/MFNsySDh3bV2qf54B3vUa6c+jtpsP4beKrF+q1fI+NrqJyofLDaIeiLOe+j9osYWClHHz4PryvFuj75U2vAZEvj/hvMGwI5e61Y9WNwqeS6pwv7vMSGEByOKg+6v/M7jmax david@desktop" >> /home/ubuntu/.ssh/authorized_keys

mkdir /mnt/data
chown ubuntu:ubuntu /mnt/data
echo "/dev/xvdf	/mnt/data	ext4	defaults,nofail,nobootwait	0	2" | tee -a /etc/fstab

apt-get update
apt-get install -y awscli git libxml2-dev libxslt1-dev nodejs npm python-dev python3-pip rubygems xpdf zlib1g-dev

cd /home/ubuntu
sudo -u ubuntu git clone https://github.com/unitedstates/inspectors-general.git
# uncomment in the event of catastrophic github failure
# sudo -u ubuntu git clone https://davidsherenowitsa.party/git/inspectors-general.git
cd inspectors-general/
pip3 install -r requirements.txt

cd /home/ubuntu
sudo -u ubuntu git clone https://github.com/konklone/oversight.garden.git
# sudo -u ubuntu git clone https://davidsherenowitsa.party/git/oversight.garden.git
cd oversight.garden
gem install bundler
bundle install
sudo -u ubuntu npm install

mount -a
ln -s /mnt/data /home/ubuntu/inspectors-general/data
ln -s /mnt/data /home/ubuntu/oversight.garden/data

sudo -u ubuntu cp config/config.yaml.example config/config.yaml
# TODO: more config
sed -i 's/127.0.0.1/search-oversight-iu2rwt666hmlxrbn2slw6zlgou.us-east-1.es.amazonaws.com/' config/config.yaml
sed -i 's/9200/80/' config/config.yaml
echo "aws:" >> config/config.yaml
echo "  region: us-east-1" >> config/config.yaml

echo "0 */3 * * * ubuntu cd /home/ubuntu/inspectors-general; /usr/bin/python3 /home/ubuntu/inspectors-general/igs; cd /home/ubuntu/oversight.garden; nodejs tasks/inspectors.js --since 1900" | crontab -
