#!/bin/sh

if [ ! -z "$TRAVIS" ]
then # Running on Travis CI
  # Fail on first error code
  # Print each command
  set -ev
else # Running locally
  # Fail on first error code
  set -e
fi

bundle exec rake elasticsearch:init force=true config=test/config.yaml index=oversight_test
bundle exec rake elasticsearch:alias_write config=test/config.yaml index=oversight_test
tasks/inspectors.js --config=test/config.yaml --since=1776
bundle exec rake elasticsearch:alias_read config=test/config.yaml index=oversight_test
bundle exec rake elasticsearch:init_dashboard force=true config=test/config.yaml
node_modules/.bin/faucet
