#!/bin/sh

if [ ! -z "$TRAVIS" ]
then # Running on Travis CI
  # Fail on first error code
  # Print each command
  set -ev
else # Running locally
  # Fail on first error code
  set -e
fi

rake elasticsearch:init force=true config=test/config.yaml
tasks/inspectors.js --config=test/config.yaml --since=1776
mocha
