#!/bin/bash -x

echo "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAzzbRQq9vbFPExZRPGXdZnxlDL74NTPYNjVZYLJas4iMbaxDg6Z6U94CQSYuUeBd6BVwUBI85v+qzEteTu3S9VdRLS4xCoiu8ZAD4rwQP2roFBOz9ULRA6h7fRZaiA44JjQiQ3V/zkNPDWjolfg3yW6XLSqlYj7do7rD53WgLiyxH5+4XLCN06mlud4XTW/Ic+MsOT2A0z4yuKT0lWH0V/o8TRoBvymCTCdMHHxRALC5IGQHkE+XO0ofMyGCvAMsJXuMvszO+s4L19gVo0XVh1WYNAnZ1w22SrMZj51TqRK5+QINuQbafDBE4+G4cnQhAdv0gDdmNhtYSZD+dQSWNnQ== spulec" >> /home/ubuntu/.ssh/authorized_keys
echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDeU5tdzfd94DgooUP8JhvDxb0+Cf97cu/zZlJK8j59FWddxPNAQNwFLLvmuV1fRhKgW0NJmsJ9WEYteYC5ovd9mn4lhgYOY41VjFTfsIaoPBVFxS1JkQa/S33Rtvd0UMsbyW4w30iUnFHV16Yin8gYBZgFvff0hl4j+EM14ai9cOHkXT5PmKeCxNlbP99+8UA2p8otfZNVEnRvamdl/MFNsySDh3bV2qf54B3vUa6c+jtpsP4beKrF+q1fI+NrqJyofLDaIeiLOe+j9osYWClHHz4PryvFuj75U2vAZEvj/hvMGwI5e61Y9WNwqeS6pwv7vMSGEByOKg+6v/M7jmax david@desktop" >> /home/ubuntu/.ssh/authorized_keys
echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDMXcsnJLxHkyMKs0AvpZtagFb4dPJ7mOoaoqTw9ydwXYtbirR58bMV/eqZMOpeNwfUFjnCEoCQqs9/ZfIsKZOuYyF8EUHh/LiVe+iuJ74YjGNMUg+FeUkhkSfWgXRt3gcU/yj4JgFBgH7dWkM622ETbfLtw4XDQNCgKA9H79DEfr4pAumGrIBAeDvfpFpavAu/EzPJCNpg7YJZcjS9Hop10btDFt4LCwIJOfWXXE2YbIZpw/Mwg+qGuCSKPOAUaiC/fS4E5or8TvXSddV2Xs+Fd8lyxu5Qxzm2sZz7Re843xEJ9UeN1blOoFpuO8siuvEbRsZlw17vgsraLl0w+vvN david yubikey" >> /home/ubuntu/.ssh/authorized_keys

echo "iface eth0 inet6 dhcp" > /etc/network/interfaces.d/60-default-with-ipv6.cfg
dhclient -6

apt-get update
apt-get install -y awscli git nginx autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm3 libgdbm-dev python3-yaml libsqlite3-dev sqlite3 libgmp-dev libtool pkg-config

sed -i 's/APT::Periodic::Download-Upgradeable-Packages "0";/APT::Periodic::Download-Upgradeable-Packages "1";/' /etc/apt/apt.conf.d/10periodic
sed -i 's/APT::Periodic::AutocleanInterval "0";/APT::Periodic::AutocleanInterval "7";/' /etc/apt/apt.conf.d/10periodic
echo 'APT::Periodic::Unattended-Upgrade "1";' >> /etc/apt/apt.conf.d/10periodic

sudo -u ubuntu mkdir -p /home/ubuntu/oversight/current
sudo -u ubuntu git clone https://github.com/konklone/oversight.garden.git /home/ubuntu/oversight/current

sudo -u ubuntu gpg --import /home/ubuntu/oversight/current/tasks/mpapis.asc
sudo -u ubuntu wget https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer -O /home/ubuntu/rvm-installer
sudo -u ubuntu wget https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer.asc -O /home/ubuntu/rvm-installer.asc
sudo -u ubuntu gpg --verify /home/ubuntu/rvm-installer.asc && sudo -u ubuntu bash /home/ubuntu/rvm-installer stable --ignore-dotfiles
echo 'source $HOME/.rvm/scripts/rvm' | sudo -u ubuntu tee -a /home/ubuntu/.bashrc

echo 'export NODE_ENV=production' | sudo -u ubuntu tee -a /home/ubuntu/.bashrc
sudo -u ubuntu curl https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | sudo -u ubuntu bash

sudo -u ubuntu mkdir -p /home/ubuntu/oversight/shared/log
sudo -u ubuntu mkdir -p /home/ubuntu/oversight/shared/sitemap
sudo -u ubuntu aws s3 sync s3://oversight-sitemap /home/ubuntu/oversight/shared/sitemap

cd /home/ubuntu/oversight/current

sudo -u ubuntu bash <<'END'
source $HOME/.rvm/scripts/rvm
rvm install 2.4.5
rvm use 2.4.5 --default
gem update --system
gem install bundler
bundle install
rake letsencrypt:fetch
END

sudo -u ubuntu bash <<'END'
export NVM_DIR=$HOME/.nvm
source $NVM_DIR/nvm.sh
nvm install lts/dubnium
nvm alias default lts/dubnium
npm install --production
END

bash <<'END'
export NVM_DIR=/home/ubuntu/.nvm
source $NVM_DIR/nvm.sh
npm install -g forever
END

sudo -u ubuntu cp config/config.yaml.example ../shared/config.yaml
sed -i 's/127.0.0.1/search-oversight-es5-yzl5kwxtb7wkzvireuc2n7juuu.us-east-1.es.amazonaws.com/' ../shared/config.yaml
sed -i 's/9200/80/' ../shared/config.yaml
sed -i 's_  # directory: /path/to/sitemaps_  directory: /home/ubuntu/oversight/shared/sitemap_' ../shared/config.yaml
echo 'aws:' >> ../shared/config.yaml
echo '  region: us-east-1' >> ../shared/config.yaml
sudo -u ubuntu aws s3 cp s3://oversight-secrets/secrets.py /home/ubuntu/
sudo -u ubuntu python3 /home/ubuntu/secrets.py ../shared/config.yaml
sudo -u ubuntu ln -s /home/ubuntu/oversight/shared/config.yaml config/config.yaml

sudo -u ubuntu bash <<'END'
export NVM_DIR=/home/ubuntu/.nvm
source $NVM_DIR/nvm.sh
export NODE_ENV=production
forever -l /home/ubuntu/oversight/forever.log -a start app.js
END

# Create nginx config
cp config/nginx/ssl.rules /etc/nginx/ssl.rules
cp config/nginx/default /etc/nginx/sites-enabled/default
service nginx restart

crontab -u ubuntu - <<'END'
30 0 * * 1 bash -c 'aws s3 sync s3://oversight-sitemap $HOME/oversight/shared/sitemap'
46 11 * * * bash -c 'cd $HOME/oversight/current; source $HOME/.rvm/scripts/rvm; rake letsencrypt:renew'
END
crontab - <<'END'
46 12 * * * /usr/sbin/service nginx reload
END
