#!/bin/bash -x

echo "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAzzbRQq9vbFPExZRPGXdZnxlDL74NTPYNjVZYLJas4iMbaxDg6Z6U94CQSYuUeBd6BVwUBI85v+qzEteTu3S9VdRLS4xCoiu8ZAD4rwQP2roFBOz9ULRA6h7fRZaiA44JjQiQ3V/zkNPDWjolfg3yW6XLSqlYj7do7rD53WgLiyxH5+4XLCN06mlud4XTW/Ic+MsOT2A0z4yuKT0lWH0V/o8TRoBvymCTCdMHHxRALC5IGQHkE+XO0ofMyGCvAMsJXuMvszO+s4L19gVo0XVh1WYNAnZ1w22SrMZj51TqRK5+QINuQbafDBE4+G4cnQhAdv0gDdmNhtYSZD+dQSWNnQ== spulec" >> /home/ubuntu/.ssh/authorized_keys
echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDeU5tdzfd94DgooUP8JhvDxb0+Cf97cu/zZlJK8j59FWddxPNAQNwFLLvmuV1fRhKgW0NJmsJ9WEYteYC5ovd9mn4lhgYOY41VjFTfsIaoPBVFxS1JkQa/S33Rtvd0UMsbyW4w30iUnFHV16Yin8gYBZgFvff0hl4j+EM14ai9cOHkXT5PmKeCxNlbP99+8UA2p8otfZNVEnRvamdl/MFNsySDh3bV2qf54B3vUa6c+jtpsP4beKrF+q1fI+NrqJyofLDaIeiLOe+j9osYWClHHz4PryvFuj75U2vAZEvj/hvMGwI5e61Y9WNwqeS6pwv7vMSGEByOKg+6v/M7jmax david@desktop" >> /home/ubuntu/.ssh/authorized_keys

apt-get update
apt-get install -y awscli git nginx autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm3 libgdbm-dev python3-yaml

sed -i 's/APT::Periodic::Download-Upgradeable-Packages "0";/APT::Periodic::Download-Upgradeable-Packages "1";/' /etc/apt/apt.conf.d/10periodic
sed -i 's/APT::Periodic::AutocleanInterval "0";/APT::Periodic::AutocleanInterval "7";/' /etc/apt/apt.conf.d/10periodic
echo 'APT::Periodic::Unattended-Upgrade "1";' >> /etc/apt/apt.conf.d/10periodic

sudo -u ubuntu git clone https://github.com/sstephenson/rbenv.git /home/ubuntu/.rbenv
sudo -u ubuntu git clone https://github.com/sstephenson/ruby-build.git /home/ubuntu/.rbenv/plugins/ruby-build
echo 'export PATH=$HOME/.rbenv/bin:$PATH' | sudo -u ubuntu tee -a /home/ubuntu/.bashrc
echo 'eval "$(rbenv init -)"' | sudo -u ubuntu tee -a /home/ubuntu/.bashrc

echo 'export NODE_ENV=production' | sudo -u ubuntu tee -a /home/ubuntu/.bashrc
sudo -u ubuntu curl https://raw.githubusercontent.com/creationix/nvm/v0.31.2/install.sh | sudo -u ubuntu bash

sudo -u ubuntu mkdir -p /home/ubuntu/oversight/current
sudo -u ubuntu mkdir -p /home/ubuntu/oversight/shared/log
sudo -u ubuntu mkdir -p /home/ubuntu/oversight/shared/sitemap
sudo -u ubuntu aws s3 sync s3://oversight-sitemap /home/ubuntu/oversight/shared/sitemap
cd /home/ubuntu/oversight/current
sudo -u ubuntu git clone https://github.com/konklone/oversight.garden.git .

sudo -u ubuntu bash <<'END'
export PATH=$HOME/.rbenv/shims:$HOME/.rbenv/bin:$PATH
rbenv install 2.2.5
rbenv global 2.2.5
gem install bundler
rbenv rehash
bundle install
rake letsencrypt:fetch
END

sudo -u ubuntu bash <<'END'
export NVM_DIR=$HOME/.nvm
source $NVM_DIR/nvm.sh
nvm install 4.4.7
nvm alias default 4.4.7
npm install --production
./node_modules/.bin/wintersmith build --config=config/blog.js
END

bash <<'END'
export NVM_DIR=/home/ubuntu/.nvm
source $NVM_DIR/nvm.sh
npm install -g forever
END

sudo -u ubuntu cp config/config.yaml.example ../shared/config.yaml
sed -i 's/127.0.0.1/search-oversight-iu2rwt666hmlxrbn2slw6zlgou.us-east-1.es.amazonaws.com/' ../shared/config.yaml
sed -i 's/9200/80/' ../shared/config.yaml
sed -i 's_  # directory: /path/to/sitemaps_  directory: /home/ubuntu/oversight/shared/sitemap_' ../shared/config.yaml
echo 'aws:' >> ../shared/config.yaml
echo '  region: us-east-1' >> ../shared/config.yaml
sudo -u ubuntu aws s3 cp s3://oversight-secrets/secrets.py /home/ubuntu/
sudo -u ubuntu python3 /home/ubuntu/secrets.py ../shared/config.yaml
sudo -u ubuntu ln -s /home/ubuntu/oversight/shared/config.yaml config/config.yaml

sudo -u ubuntu bash <<'END'
export NVM_DIR=/home/ubuntu/.nvm
source $NVM_DIR/nvm.sh
export NODE_ENV=production
forever -l /home/ubuntu/oversight/forever.log -a start app.js
END

# Create nginx config
cp config/nginx/ssl.rules /etc/nginx/ssl.rules
cp config/nginx/default /etc/nginx/sites-enabled/default
service nginx restart

crontab -u ubuntu - <<'END'
30 0 * * 1 bash -c 'aws s3 sync s3://oversight-sitemap $HOME/oversight/shared/sitemap'
46 11 * * * bash -c 'cd $HOME/oversight/current; export PATH=$HOME/.rbenv/shims:$HOME/.rbenv/bin:$PATH; rake letsencrypt:renew'
END
